### ISSUE TITLE
danger_disable_hostname_verification doesn't seem to work

### ISSUE THREAD

**Issue by dylemma** [hyperium/hyper-tls#10]
```rust
let mut https_connector = ::hyper_tls::HttpsConnector::new(4, &core.handle()).unwrap();
https_connector.danger_disable_hostname_verification(true);
let client = ::hyper::Client::configure()
    .connector(https_connector)
    .build(&core.handle());
```

my Cargo.toml contains
```toml
hyper = "0.11"
hyper-tls = "0.1.2"
```

If I try to use this `client` to connect to `https://in-house-server-with-dubious-self-signed-cert/yadda/yadda`, I get

> Io(Error { repr: Custom(Custom { kind: Other, error: Error { repr: Os { code: -2146762487, message: "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider." } } }) })

Just in case, I tried calling `danger_disable_hostname_verification(false)` but that didn't change anything.

Am I missing something? Is the intent of `danger_disable_hostname_verification` actually to ignore the certificate/trust process, or is it some other part of the SSL process that I'm misunderstanding?

**Comment by seanmonstar** [comment]
That method is used to disable verifying that the certificate is issued for the domain requested. It still will validate that the certificate is trusted by a root authority.

You may wish to look at the reqwest crate, which makes it easier to add root certificates.

**Comment by dylemma** [comment]
Thanks for the pointer, I'll check that out.
