### ISSUE TITLE
HttpsConnector break body stream

### ISSUE THREAD

**Issue by d33d33** [hyperium/hyper-tls#14]
Hello,

I am trying to `POST` a streamed payload to an HTTPS endpoint, while everything is fine for HTTP, in HTTPS the event loop seems to deadlock :/

Running the following code produce
https://gist.github.com/d33d33/2fb4b264ecdb4a4d787925f993295929
```
POLL 0
POLL 1
POLL 2
```
and wait forever, while running it with an HttpConnector produce
```
POLL 0
POLL 1
POLL 2
POLL 3
POLL 4
DONE
Response: 200 OK
```

**Comment by seanmonstar** [comment]
Hm, is it possible to run this with logs enabled? Such as add `env_logger`, and running with `RUST_LOG=hyper`?

**Comment by d33d33** [comment]
Sure :)
https://gist.github.com/d33d33/a55fe1d58b979d17f6d4457715232c2e

Seems to enter in an infinite loop

**Comment by seanmonstar** [comment]
Great, with those logs I was able to track it down! Turns out it was a bug in hyper when the IO stream didn't support vectored writes.

**Comment by d33d33** [comment]
\o/

For reference https://github.com/hyperium/hyper/commit/731096947d0704de58b75d17e05af956bcb21bd9
