### ISSUE TITLE
Publish new version on crates.io to export `native-tls` error

### ISSUE THREAD

**Issue by niklasad1** [hyperium/hyper-tls#15]
Hey,

This [commit](https://github.com/hyperium/hyper-tls/commit/5a8bed52c7c38d0b0ac735315e6fabecec2bcb6e) exports `native-tls` errors which I think is a major improvement and should therefore be published on crates.io!

**Comment by seanmonstar** [comment]
Good point, I had forgotten about it! Published just now as 0.1.3.
