### ISSUE TITLE
Enforce TLS By Default

### ISSUE THREAD

**Issue by imnotbad** [hyperium/hyper-tls#18]
Currently `hyper-tls` will fall back to using HTTP if the URL passed to the connect function is not using the HTTPS scheme, this is probably not what people expect and it's not mentioned in the documentation anywhere as far as i can see. It might be worth erroring out if the URL scheme is not HTTPS by default in order to prevent people from unintentionally sending data in the clear when, for example, they don't control the URL passed into their application.

This would however be an API breaking change and i'm not sure if that is acceptable for the project right now. At the very least it would be nice to have an optional flag that forces the use of HTTPS, as well as mentioning this behaviour in the documentation so developers are aware of `hyper-tls`'s default behaviour in situations where a URL using the HTTP scheme is used.

**Comment by seanmonstar** [comment]
Both are good points (clarifying the default behavior, and adding an option to disable HTTP support).

**Comment by seanmonstar** [comment]
Yea, I think I'd prefer the current default behavior.

**Comment by imnotbad** [comment]
Done in PR https://github.com/hyperium/hyper-tls/pull/19
