### ISSUE TITLE
Implement AsyncRead + AsyncWrite from tokio_io

### ISSUE THREAD

**Issue by mgattozzi** [hyperium/hyper-tls#2]
The recent [PR](https://github.com/hyperium/hyper/pull/1093) to Hyper has caused a breaking change that makes this not work with the code from that commit onwards. It seems like the only thing needed to get hyper-tls working again is for it to implement the AsyncRead and AsyncWrite traits from tokio_io. This will allow it to work as a connector again for Hyper.

**Comment by seanmonstar** [comment]
Thanks for pointing this out. I've just pushed updated impls for this crate.

**Comment by mgattozzi** [comment]
No problem! Thanks for updating them so quickly, this helps a lot.
