### ISSUE TITLE
client: consider exposing a builder for HttpsConnector

### ISSUE THREAD

**Issue by lucab** [hyperium/hyper-tls#3]
It looks like `HttpsConnector` internally goes through a `TlsConnector` builder, but doesn't expose it to library users. I was looking into how to tell hyper-tls about custom CA and cert-chains, and it seems that it is not currently possible without having access to the chain of builders up to `TlsConnectorBuilderExt.builder_mut()`. If so, I'd like to have some builder-pattern or similar method to tweak such details.

I'm still not very familiar with this crate, so pardon me if I missed some already existing details.

**Comment by seanmonstar** [comment]
A builder and configuration would probably be a really good idea! The purpose of this crate was mostly to be an example and provide the ability to get up and running quickly in the default case.

**Comment by cavedweller** [comment]
echoing this desire! If I have time, I'll take a look at it this weekend.

**Comment by lucab** [comment]
Closing as implemented now, see https://github.com/hyperium/hyper-tls/pull/7#issuecomment-308776712.
