### ISSUE TITLE
Seems strange to have this crate separated from hyper.

### ISSUE THREAD

**Issue by thedodd** [hyperium/hyper-tls#31]
IMHO, having this crate separated out from hyper doesn't really accomplish too much other than adding additional time and effort to basic usage. Defaulting to https support, but allowing a user to opt out, would seem to be a far more logical (and secure) pattern.

1. if someone wants to use different connectors, they would certainly still be able to, and perhaps that is when they would opt out of the "https" feature.
2. adoption of hyper would be faster and easier. E.G., I found out that I needed a different support crate for Hyper TLS when using the client and it failed saying that only http was supported.
I know that there is info on the website, but I did not see it in the docs, and I didn't read the website until later.
3. batteries included seems to be a big part of rust. HTTPS isn't even a battery though. It is standard these days.

All in all, thank you @seanmonstar and everyone else who has contributed to the Hyper ecosystem. It is certainly foundational to the Rust web ecosystem. I hope my feedback here is constructive and valuable.

**Comment by seanmonstar** [comment]
For reference, the decision is written up in this issue: https://github.com/hyperium/hyper/issues/985
