### ISSUE TITLE
New release for 'vendored' feature

### ISSUE THREAD

**Issue by DarrenTsung** [hyperium/hyper-tls#32]
Hi @seanmonstar, are you planning to make a new release anytime soon? We plan to use the 'vendored' feature added [here](https://github.com/hyperium/hyper-tls/commit/dc8a13409b753ce212aada925ad5edb58e185349) and it is not currently published on crates.io.

**Comment by seanmonstar** [comment]
Woops, certainly! Forgot about the changes here, I've just published 0.3.1.
