### ISSUE TITLE
Missing commits and tag for release 0.3.1

### ISSUE THREAD

**Issue by dekellum** [hyperium/hyper-tls#34]
The latest hyper-tls-0.3.1 release has .cargo_vcs_info.json with:

~~~ json
{
  "git": {
    "sha1": "3d1f412d171cd8d9a5efc9396c85ef084a9ef4bd"
  }
}
~~~

...but commit 3d1f412d171cd8d9a5efc9396c85ef084a9ef4bd isn't found here.  Current master is dc8a13409b753ce212aada925ad5edb58e185349.  Forgot to push it?

**Comment by seanmonstar** [comment]
Yep, ran `cargo publish` and then forgot to `git push`. Fixed!
