### ISSUE TITLE
error of same type of different paths and question of Cargo.toml git source rev

### ISSUE THREAD

**Issue by king6cong** [hyperium/hyper-tls#4]
error:
```
.connector(::hyper_tls::HttpsConnector::new(4, &core.handle()))
^^^^^^^^^ expected struct `hyper::uri::Uri`, found struct `hyper::Uri`
```

repo to reproduce this error: 

https://github.com/king6cong/tls-test

Funny thing is it will be ok to use:
```
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
``` 
but error occurs:

```
hyper = { git = "https://github.com/hyperium/hyper", rev = "3da720a99fab9cf6ecf8a206bb22c826ebb74992" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls", rev = "74aefbe500df5bb2d9a87844580b4ac21d49f134" }
```

while master rev should be equal to the specified rev at this moment.

Some questions:
1. Will same type of different paths cause problems like this?
2. What is the difference between `With rev specified` or `without rev specified` when rev chosen should be the same anyway. (I check Cargo.lock)

**Comment by seanmonstar** [comment]
This may be an issue for Cargo. For your project, you could check the Cargo.lock file into git, instead of using rev in the Cargo.toml.

**Comment by king6cong** [comment]
Yes.
But what can we do to avoid `same type of different paths` problems?

**Comment by seanmonstar** [comment]
As I said, you can lock the revision with the `Cargo.lock` file, and not have a `rev` in the `Cargo.toml`.

**Comment by king6cong** [comment]
Yes, I know how to solve this problem. 
I mean I wonder how to approach the `same type of different paths` problem on the language level.
Thanks.
