### ISSUE TITLE
Some way to force connecting through a TLS connection would be nice

### ISSUE THREAD

**Issue by whataloadofwhat** [hyperium/hyper-tls#41]
I tried using this library to connect to a websocket server with TLS, which uses `wss` as a scheme. As the scheme is not `https` it is falling back to a regular `http` connection and then failing because it is actually `https`. It seems impossible to connect to a websocket server with the `wss` scheme with this connector unfortunately.

For now I've made my own copy of the `HttpsConnector<T>` which works for this use case, but I feel like there should be a connector here which will allow this. Perhaps a `ForceHttpsConnector<T>` or something, which will just presume that the connection is `https` and then error later down the line if it turns out that it actually isn't rather than trying to fail early.

Alternatively, include `wss` in the check for `is_https`, but that feels comparatively short sighted.

**Comment by seanmonstar** [comment]
Oh I see what you mean. This connector currently supports both TLS and plaintext, and you'd ideally just want one that only uses TLS.

The simplest option could be to add some `force_https` option, but it still yields `MaybeTlsStream` values.

Another option is to add a similar `HttpsOnlyConnector`...

**Comment by seanmonstar** [comment]
A `force_https` option has been added.
