### ISSUE TITLE
Get rid of BoxError

### ISSUE THREAD

**Issue by MOZGIII** [hyperium/hyper-tls#57]
Why use `BoxError` in the `HttpsConnector` if an enum would work and won't be too complicated?

In my current code, I can't just use `?` or `.into` on the error cause it's not `Sized`, and, although I can work around it pretty easily, I see no reason why we shouldn't use enum.

**Comment by seanmonstar** [comment]
The reason for its use here is I didn't want to "wrap" the inner connectors errors, but instead just passing them on.

**Comment by MOZGIII** [comment]
Well, yeah, I figured. Is there a reason why you don't want to wrap the errors?
I can send you a PR with the code with the wrapping if you'd like.

**Comment by seanmonstar** [comment]
How come it can't be converted using `?` or `into`?

**Comment by MOZGIII** [comment]
![image](https://user-images.githubusercontent.com/265507/70839425-ca970080-1e1d-11ea-9466-652a4492a830.png)

**Comment by MOZGIII** [comment]
I'm using `failure::Error` crate. The workaround is to `.map_err(Error::from_boxed_compat)` , but it's not pretty.

**Comment by MOZGIII** [comment]
Submitted a PR.
I don't see a reason why one would want to not wrap errors in this case, so if you have one I'm really curious.

**Comment by seanmonstar** [comment]
Mostly I didn't want to wrap if there was no additional context to add, since you'd need to look down the source chain one more time for `err.downcast` to match the wrapped error.

**Comment by MOZGIII** [comment]
A mechanism like https://github.com/rust-lang/rust/pull/58289 resolves that issue almost entirely, and to avoid doing a `match` over the subtypes one could just to `err.source().downcast()` - that is not much more verbose but does just pretty much the same as `downcast` on currently present `BoxError` (you couldn't check for `ForceHttpsButUriNotHttps` that way too anyway).
