### ISSUE TITLE
Enable all protocols supported by upstream hyper via ALPN by default

### ISSUE THREAD

**Issue by nagisa** [hyperium/hyper-tls#61]
Disclaimer: I didn’t look at the code from this crate for too long.

This crate appears to be pretty much the most hands free way to get https support with hyper. However, a caveat is that this does not do any protocol negotiation and thus hyper is forced to always use http1.1.

I think it should, by default, do most of this kind of setup for the user without any additional effort on the user end.

**Comment by CryZe** [comment]
Isn't the problem that native-tls doesn't support ALPN? (Because it's only implemented on a few of the underlying native implementations).

**Comment by seanmonstar** [comment]
Correct, native-tls doesn't have ALPN support, and won't until all the backends have support added (see https://github.com/sfackler/rust-native-tls/pull/113).

**Comment by RAnders00** [comment]
Do we want to reopen this given that `native-tls` added ALPN support now? https://github.com/sfackler/rust-native-tls/blob/master/CHANGELOG.md#v027 The documentation around the new feature seems to be rather lackluster though, the `alpn` flag is only mentioned in the changelog and not on the docs.rs or in the README.
