### ISSUE TITLE
Cannot connect to URLs with IP literals

### ISSUE THREAD

**Issue by edevil** [hyperium/hyper-tls#68]
Connecting to URLs like `https://[2606:4700:4700::1111]/` fails due to the hostname verification (SNI). This library passes the `host()` returned by the URI package [here](https://github.com/hyperium/hyper-tls/blob/master/src/client.rs#L134), but the value returned for this URL is `[2606:4700:4700::1111]/`.

This fails TLS hostname verification because not only do the brackets have to be removed, but the IPv6 literal also has to observe specific rules regarding zero compression and suppression. [spec](https://tools.ietf.org/html/rfc6125)

In this case the correct name to pass to the TLS library would be `2606:4700:4700:0:0:0:0:1111`.

**Comment by seanmonstar** [comment]
Fixed by #69
