### ISSUE TITLE
Specifying root certificates

### ISSUE THREAD

**Issue by rdelfin** [hyperium/hyper-tls#70]
This might just be my inability to search through this code properly, but I'll just ask. Does this support using custom root certificates?

**Comment by seanmonstar** [comment]
This can be done with [`TlsConnectorBuilder::add_root_certificate`](https://docs.rs/native-tls/0.2.4/native_tls/struct.TlsConnectorBuilder.html#method.add_root_certificate).

**Comment by rdelfin** [comment]
@seanmonstar just to clarify, do you mean creating a new TlsConnector and passing it into `new_with_connector()` ? Or rather, how does the library let you pass in custon TlsConnectors when creating an HttpsConnector?
