### ISSUE TITLE
recent upgrade to tokio-native-tls breaks crates that depend on hyper-tls

### ISSUE THREAD

**Issue by EverlastingBugstopper** [hyperium/hyper-tls#71]
i see this crate was released an hour ago - seems to have broken my crates relying on `reqwest`.

see https://github.com/seanmonstar/reqwest/issues/971 for report on reqwest crate

more specifically - it looks like `std::convert::From<(connect::HttpConnector, tokio_tls::TlsConnector)>` is no longer implemented (i think [this commit](https://github.com/hyperium/hyper-tls/commit/7c9adcdebba980ed3d3a6190480fafe37628264e)) which is causing this issue

**Comment by ramosbugs** [comment]
the `oauth2` and `openidconnect` crates I maintain are similarly affected:
https://travis-ci.org/github/ramosbugs/oauth2-rs/jobs/705496763
https://travis-ci.org/github/ramosbugs/openidconnect-rs/jobs/705496401

thanks @EverlastingBugstopper for tracking down the root cause!

**Comment by seanmonstar** [comment]
Oh no, sorry about that. @LucioFranco does this look like it shouldn't have broken? I'll try to publish a revert ASAP.

**Comment by LucioFranco** [comment]
@seanmonstar probably, my fault for not checking that From impl. It is a breaking change since the from now wants the `TlsConnector` from `tokio_native_tls` not `tokio_tls` crate.

**Comment by LucioFranco** [comment]
I left a note on the PR with what I think we should do.

**Comment by LucioFranco** [comment]
The real solution should be to just swap out `tokio-tls` for `tokio-native-tls` since it was a crate rename. Sorry about the trouble!

**Comment by LucioFranco** [comment]
The crates should be 1-1 the same.

**Comment by kaj** [comment]
> The crates should be 1-1 the same.

Maybe doing a patch release on `tokio-tls` that reexports `tokio-native-tls` as itself would fix the problem in a nice way until everything that depends on `tokio-tls` has new releases?

**Comment by LucioFranco** [comment]
@kaj I believe that would still be a breaking change? Since, a reexport doesn't change the type?

**Comment by seanmonstar** [comment]
I've yanked v0.4.2, so hopefully no one *new* should be downloading the broken version. I think though we have to release a v0.4.3 in order to fix it for those who already have, right? Or I suppose you could also just run `cargo update -p hyper-tls 0.4.1`.

**Comment by LucioFranco** [comment]
@seanmonstar we could cherrypick the ipv6 commit for a 0.4.3, then place the tokio-native-tls commit into a 0.5 release.

**Comment by seanmonstar** [comment]
That sounds good!

**Comment by seanmonstar** [comment]
Ok, published v0.4.3 that should be better for everyone!
