### ISSUE TITLE
Automatic client/server certificate reloading.

### ISSUE THREAD

**Issue by sergeykhegay** [hyperium/hyper-tls#75]
Hi, what would be the best approach to automatically reload certificates on a running server/client? The use case is for environments where certs are refreshed pretty frequently -- once a day.

For example, in Golang, when configuring TLS is as possible to provide callbacks which are called when certificate is needed. See `GetCertificate`, `GetClientCertificate` https://golang.org/pkg/crypto/tls/#Config.

**Comment by sergeykhegay** [comment]
I was able to do this with `hyper-rustls`.

**Comment by jacob-pro** [comment]
@sergeykhegay please could you explain how you did this with rustls?
