### ISSUE TITLE
Upgrade to hyper 0.14

### ISSUE THREAD

**Issue by jensim** [hyperium/hyper-tls#76]
Please release a upgraded version depending on tokio:0.3

Blocked by:
- [ ] hyper & h2

**Comment by mleonhard** [comment]
I'm blocked by this.  I'm writing an http server library with tokio 0.3 and wish to use reqwest in the tests.  [A fix](https://github.com/hyperium/hyper-tls/pull/77) has been ready for 24 days.  Is there anything I can do to help get a fix approved faster?

**Comment by seanmonstar** [comment]
We are working on the hyper 0.14 milestone, which must be released before hyper-tls can use the updates.

**Comment by mathias-arm** [comment]
Maybe this should be renamed to "Upgrade to Tokio 1.0" (https://tokio.rs/blog/2020-12-tokio-1-0) which hype v0.14 (https://seanmonstar.com/post/638320652536922112/hyper-v014). Bytes 1.0 is also part of the updates.

**Comment by gabhijit** [comment]
Submitted - https://github.com/hyperium/hyper-tls/pull/83 for this issue.

**Comment by seanmonstar** [comment]
Done in #79
