### ISSUE TITLE
Write response to string

### ISSUE THREAD

**Issue by Alko89** [hyperium/hyper-tls#8]
I am trying to parse the HTML response I get from hyper request, but in the example, the response is written to stdout.
I'm new to rust and don't know how can I write the response to a string to manupulate it.

**Comment by seanmonstar** [comment]
This repo is for the TLS HttpsConnector, so I'm going to close. But to quickly try to provide an answer to your question:

```rust
use std::str;

res.body().concat2().and_then(|bytes| {
    match str::from_utf8(&bytes) {
        Ok(s) => {
            // s is `&str`
            // maybe you only need a reference to str, and can do your work here
            // or maybe you wish to convert to a `String`, and send else where
            Ok(s.to_string())
        },
        Err(err) => {
            // the body wasn't UTF-8
            // deal with this error however you'd like
            // this example just returns the error to be handled by someone else
            Err(err)
        }
    }
})
```

**Comment by Alko89** [comment]
Sorry, I guess I was desperate. I want to write a simple web crawler in rust and got completely stuct fur hours with the most trivial task. I didn't know there is a to_string method. Thanks!
